#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Apr 10 11:49:22 JST 2025
# SW Build 3788238 on Tue Feb 21 19:59:23 MST 2023
#
# IP Build 3783773 on Tue Feb 21 23:41:56 MST 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim TB_MAC_behav -key {Behavioral:sim_1:Functional:TB_MAC} -tclbatch TB_MAC.tcl -log simulate.log"
xsim TB_MAC_behav -key {Behavioral:sim_1:Functional:TB_MAC} -tclbatch TB_MAC.tcl -log simulate.log

